name: (Default) Swappi subgraph Continues Deployment

on:
  push:
    branches:
      - 'default'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: SSH & Run
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY_I32XLARGE }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-13-229-104-215.ap-southeast-1.compute.amazonaws.com "
            cd /base/app/v2-subgraph
            git reset HEAD --hard
            git fetch origin default
            git checkout default
            git pull --rebase origin default
            yarn
            GRAPH_NODE_PORT=8020 IPFS_PORT=5001 yarn ship
          "
